name: Deploy Rice and Beans

on:
  push:
    branches:
      - main
      - dev

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          LOWERCASE_USER=$(echo "${GITHUB_ACTOR}" | tr '[:upper:]' '[:lower:]')
          docker buildx build \
            --tag ghcr.io/$LOWERCASE_USER/deploy_rice_and_beans:latest \
            --tag ghcr.io/$LOWERCASE_USER/deploy_rice_and_beans:${GITHUB_SHA} \
            --push .

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Create SSH Key from Secret
        run: |
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/vps-2
          chmod 600 ~/.ssh/vps-2

      - name: Add VPS and GitHub to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Create Environment Variables File
        run: |
          BASE_DIR="/var/www/deploy_rice_and_beans"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TARGET_DIR="$BASE_DIR/prod"
            PORT="8000"
          else
            TARGET_DIR="$BASE_DIR/dev"
            PORT="8001"
          fi
          echo "BASE_DIR=$BASE_DIR" > ./envfile
          echo "TARGET_DIR=$TARGET_DIR" >> ./envfile
          echo "PORT=$PORT" >> ./envfile
          echo "IMAGE=ghcr.io/${{ github.actor }}/deploy_rice_and_beans:latest" >> ./envfile
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Transfer envfile to VPS
        run: |
          scp -i ~/.ssh/vps-2 ./envfile ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/envfile

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/vps-2 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
              source /home/${{ secrets.VPS_USER }}/envfile
              
              # Criar diretório com sudo
              sudo mkdir -p $TARGET_DIR
        
              # Ajustar permissões no diretório (se necessário)
              sudo chown -R $USER:$USER $TARGET_DIR
        
              # Clonar ou atualizar o repositório
              if [ ! -d "$TARGET_DIR/.git" ]; then
                sudo git clone git@github.com:${{ github.actor }}/${{ github.repository }}.git $TARGET_DIR
              fi
        
              cd $TARGET_DIR
              sudo git pull
              sudo docker-compose up -d --build
            EOF